import { Inter } from "next/font/google";
import "./globals.css";
import Facebook from "@/components/FacebookMessenger";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Plugin Facebook Messenger",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Facebook />
      </body>
    </html>
  );
}
